AWSTemplateFormatVersion: "2010-09-09"
Description: cf tutorial stack
Parameters:
  Prefix:
    Type: String
    Default: testing
    Description: Prefix Name
Resources:
  Ec2SecurityGroupApp:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "${Prefix}_app"
      GroupDescription: "web server security group"
      VpcId: "vpc-05ab9683c7db32a37"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}_app"
  Ec2InstanceServer:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      ImageId: "ami-06cd52961ce9f0d85"
      InstanceType: "t2.micro"
      KeyName: "udemysample2"
      SecurityGroupIds:
        - !Ref Ec2SecurityGroupApp
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}_app"
